### ISSUE TITLE
Unable to break all but MMA .mrc files

### ISSUE THREAD

**Issue by amberbilley** [Thomas-J-Watson-Library/Marc-Record-Sets#1]
I want to edit these records using MarcEdit, but I am unable to break any of the mrc files except for the MMA_pubs_records_2020_)04_fulltext (1).mrc file. For all other files I get the following message:

-11 records were processed in 0.002000 seconds.

and no .mrk file is created. My colleagues tried and experienced the same issues.

**Comment by blueherw** [comment]
We are working on this. For the time being, we've uploaded .zip files that include these record sets in .mrc, .mrk, and .rec. The Onestar, TOAH, State Dept, and CCT PDFs (most recent) have all been updated. Thanks for letting us know!

**Comment by blueherw** [comment]
All record sets (other than the Met Pubs) have been updated with a zip file that includes .mrk, .mrc, and .rec files.
